name: Project Checks

on:
  pull_request:
    branches: [ main, develop ]
    
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: True

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  check-projects:
    name: Check Projects
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@2008f912f56e61277eefaac6d1888b750582aa16
      
    # Add Nuget to the PATH: https://github.com/warrenbuckley/Setup-Nuget
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Create tools folder
      run: mkdir ./tools
      
    - name: Checking out repo
      uses: actions/checkout@v2
      with:
        repository: Intrapost/Tools
        path: ./tools
        ref: main
        token: ${{ github.token }}
    
    - name: Restore Nuget packages
      run: nuget restore ./tools/ProjectChecker/ProjectChecker.sln
    
    - name: Building Project Checker
      run: msbuild ./tools/ProjectChecker/ProjectChecker.sln /property:Configuration=Release

    - name: Create build folder
      run: mkdir ./build

    - name: Checking out repo
      uses: actions/checkout@v2
      with:
        path: ./build
      
    - name: Checking for Prefer 32-bit enabled
      working-directory: ./build
      run: Start-Process -NoNewWindow ../tools/ProjectChecker/bin/Release/netcoreapp3.1/ProjectChecker.exe check-prefer-32-bit-disabled
      
    - name: Checking for project name/folder missmatch
      working-directory: ./build
      run: Start-Process -NoNewWindow ../tools/ProjectChecker/bin/Release/netcoreapp3.1/ProjectChecker.exe check-directory-name
      
    - name: Checking for disabled optimization
      working-directory: ./build
      run: Start-Process -NoNewWindow ../tools/ProjectChecker/bin/Release/netcoreapp3.1/ProjectChecker.exe check-optimization-disabled
      
    - name: Checking for full debugging information
      working-directory: ./build
      run: Start-Process -NoNewWindow ../tools/ProjectChecker/bin/Release/netcoreapp3.1/ProjectChecker.exe check-full-debug-info-enabled
        
